In [ ]:
import numpy as np
numbers = np.random.randint(1, 100, 15)
print(numbers)
odd_even = numbers % 2 == 0
print(odd_even)
print(numbers[odd_even])
print(numbers[numbers % 2 == 1])  # boolean indexing

In [ ]:
numbers = np.random.randint(-100, 100, 15)
print(numbers)
positives = numbers[numbers > 0]
negatives = numbers[numbers < 0]

print(positives, negatives, sep = '\n')

In [ ]:
numbers[numbers < 0] *= -1
print(numbers)

In [14]:
names = np.array(['Harry McGuire', 'Marcus Rashford', '', 'Paul Pogba', 'David De Gea'])
ages = np.array([27, -22, 0, 26, 280])

# change empty name to 'John Doe'
names[names == ''] = 'John Doe'
print(names)
# change invalid ages to 0 or 150 correspondingly
ages[ages < 0] = 0
ages[ages > 150] = 150
print(ages)

['Harry McGuire' 'Marcus Rashford' 'John Doe' 'Paul Pogba' 'David De Gea']
[ 27   0   0  26 150]


In [24]:
y = np.array([0., 1.3, 5. , 10.9, 18.9, 28.7, 40.]) 
t = np.array([0., 0.49, 1. , 1.5 , 2.08, 2.55, 3.2])
v = np.array([0, 0, 0, 0, 0, 0, 0])
for i in range(1, len(y)):
    v[i] = (y[i] - y[i-1]) / (t[i] - t[i-1])
print(v)

[ 0  2  7 11 13 20 17]


In [16]:
v = np.zeros(len(y))
v[1:] = (y[1:] - y[:-1]) / (t[1:] - t[:-1])
print(v)

[ 0.          2.65306122  7.25490196 11.8        13.79310345 20.85106383
 17.38461538]


In [22]:
a = np.array(['A', 'BBB', '', 'C', 'DE'])
a[a == ''] = 'John Doe'
print(a)

['A' 'BBB' 'Joh' 'C' 'DE']


In [25]:
a = [2, '7', 6.0]
b = np.array(a)
print(b)

['2' '7' '6.0']


In [32]:
# 2d array
# create 2d array from 2d list
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = np.array(a)
print(b)
print(np.shape(b))
a = [1, 2, 3, 4, 5, 6]
b = np.array(a)
print(b, np.shape(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[1 2 3 4 5 6] (6,)


In [31]:
c = b.reshape(2, 3)
d = b.reshape(1, 6)
e = b.reshape(6, 1)
print(c, np.shape(c))
print(d, np.shape(d))
print(e, np.shape(e))

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2 3 4 5 6]] (1, 6)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] (6, 1)


In [37]:
print(np.zeros((2, 3)))
print(np.ones((6, 2), dtype=int))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [38]:
matrix = np.random.randint(1, 100, (3, 3))
print(matrix)

[[56  4 52]
 [32 99 25]
 [97 95  1]]


In [40]:
# Indexing
print(matrix[1][1])
print(matrix[1, 1])

99
99


In [41]:
matrix = np.random.randint(10, 100, (4, 4))
print(matrix)

[[29 72 87 38]
 [53 23 77 76]
 [42 41 97 31]
 [86 27 54 27]]


In [45]:
col1 = matrix[:, :2]
print(col1)

[[29 72]
 [53 23]
 [42 41]
 [86 27]]


In [46]:
matrix[:2, :2] = 0
print(matrix)

[[ 0  0 87 38]
 [ 0  0 77 76]
 [42 41 97 31]
 [86 27 54 27]]


In [ ]:
# Create an 8 × 8 array with ones on all the edges and zeros everywhere else. 
# Create an 8 × 8 array of integers with a checkerboard pattern of ones and zeros. 
a = np.ones((8, 8), dtype=int)
a[1:-1, 1:-1] = 0
print(a)

In [ ]:
a = np.ones((8, 8), dtype=int)
a[::2, 1::2] = 0
a[1::2, ::2] = 0
print(a)

In [53]:
a = ([1, 0] * 4 + [0, 1] * 4) * 4
a = np.array(a).reshape(8, 8)
print(a)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
