In [1]:
import numpy as np

# Create array from a list
a = [1, 2, 3, 4]
b = np.array(a)
print(a, b, sep='\n')

[1, 2, 3, 4]
[1 2 3 4]


In [12]:
a = np.arange(10)
print(a)
b = np.arange(10, 20)
print(b)
c = np.concatenate((a, b))
print(c)
d = np.arange(0, 20, 2)
print(d)
e = np.arange(1, 20, 2)
print(e)
f = np.arange(0, 1, 0.1)
print(f)
# np.arange(start, end, step)

[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [14]:
a = np.linspace(0, 9, 10, dtype=int) # start, end, number of elements
print(a)
f = np.linspace(0, 1, 10, endpoint=False)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [21]:
c = np.logspace(1, 10, 10, base=2, dtype=int)    
print(c)
d = np.logspace(0, 5, 6, dtype=int)
print(d)

[   2    4    8   16   32   64  128  256  512 1024]
[     1     10    100   1000  10000 100000]


In [22]:
# Generate following numbers: 9, 27, 81, 243, 729
e = np.logspace(2, 6, 5, base=3, dtype=int)     
print(e)

[  9  27  81 243 729]


In [25]:
zeros = np.zeros(10)
ones = np.ones((3, 3), dtype=int)
print(zeros)
print(ones)  

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [28]:
a = np.arange(5)
b = np.arange(5, 10)
print(a, b, sep='\n')
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

[0 1 2 3 4]
[5 6 7 8 9]
[ 5  7  9 11 13]
[-5 -5 -5 -5 -5]
[ 0  6 14 24 36]
[0.         0.16666667 0.28571429 0.375      0.44444444]
[0 0 0 0 0]
[0 1 2 3 4]
[     0      1    128   6561 262144]


In [30]:
print(a)
print(a + 2)
print(a - 2)    
print(a * 2)
print(a / 2)
print(a // 2)
print(a % 2)
print(a ** 2)
print(2 ** a)

[0 1 2 3 4]
[2 3 4 5 6]
[-2 -1  0  1  2]
[0 2 4 6 8]
[0.  0.5 1.  1.5 2. ]
[0 0 1 1 2]
[0 1 0 1 0]
[ 0  1  4  9 16]
[ 1  2  4  8 16]


In [31]:
b = (a * 2 - 15) / 3
print(b)

[-5.         -4.33333333 -3.66666667 -3.         -2.33333333]


In [32]:
c = a % 2 == 0
print(c)

[ True False  True False  True]
