In [ ]:
f = open('../Dataset/agencies.txt', 'r')
contents = f.read() # read the entire file into a string
print(contents)

In [ ]:
f = open('../Dataset/agencies.txt', 'r')
lines = f.readlines() # read the entire file into a list of strings
for li in lines:
    print(li[:-1]) # remove the newline character

In [7]:
f = open('../Dataset/agencies.txt', 'r')
line = f.readline() # read one line at a time
while line:
    if 'authority' in line.lower():
        print(line[:-1])
    line = f.readline()

The Triboro Bridge and Tunnel Authority
The Metropolitan Transit Authority
The Port Authority of New York and New Jersey


In [ ]:
# Read authors.txt, print authors that uses gmail
# Output example:
# Name                  Email
# Paul Bakaus           paul.bakaus@gmail.com
# Richard Worth         rdworth@gmail.com
f = open('../Dataset/authors.txt', 'r')
lines = f.readlines()
print(f'{"Name":20}{"Email":20}')
for li in lines:
    if 'gmail' in li.lower():
        name = li.split('<')[0][:-1]
        email = li.split('<')[1][:-2]
        print(f'{name:20}{email:20}')

In [12]:
f = open('../Dataset/falling.txt', 'r')
lines = f.readlines()[5:]   # read all lines & skip the first 5 lines

falling_data = []

for li in lines:
    numbers = li[:-1].split()
    falling_data.append(list(map(lambda x: float(x), numbers)))

for row in falling_data:
    print(row)

[0.0, 0.0, 180.0, 3.5]
[1.0, 0.5, 185.0, 4.5]
[2.0, 0.7, 192.0, 5.0]


In [2]:
import numpy as np
falling_data = np.loadtxt('../Dataset/falling.txt', skiprows=5)
print(falling_data)

[[  0.    0.  180.    3.5]
 [  1.    0.5 185.    4.5]
 [  2.    0.7 192.    5.2]]


In [16]:
data_points, times, heights, uncertainties = np.loadtxt('../Dataset/falling.txt', skiprows=5,       
                                                        unpack=True)
print(heights, uncertainties)

[180. 185. 192.] [3.5 4.5 5.2]


In [17]:
heights, uncertainties = np.loadtxt('../Dataset/falling.txt', skiprows=5, usecols=(2, 3), unpack=True)
print(heights, uncertainties)

[180. 185. 192.] [3.5 4.5 5.2]


In [ ]:
students_data = np.loadtxt('../Dataset/gradebook.csv', skiprows=1, delimiter=',', dtype=str)
for student in students_data:
    print(student)

In [ ]:
codes, names, grades = np.loadtxt('../Dataset/gradebook.csv', skiprows=1, delimiter=',', 
                                  usecols=(2, 3, 4), unpack=True, dtype=str)
# Fix empty grade => 0.0
grades[grades == ''] = '0.0'    # boolean indexing
# Fix empty code => GCHXXXXX
codes[codes == ''] = 'GCHXXXXX'
print(grades, codes, sep='\n')
# Fix invalid grade (>10) => 10.0
grades = np.array(list(map(lambda x: float(x) if float(x) <= 10 else 10.0, grades)))
print(grades)

In [ ]:
import csv

f = open('../Dataset/gradebook.csv', 'r')
reader = csv.reader(f)
next(reader)        # skip the header

students_data = []
for row in reader:
    students_data.append(row)

for student in students_data:
    print(student)